OBJS = file1 file2 file3 
CC = gcc


all: file1 file2 file3 file4

file1:
	$(CC) -o file1 1/1.c
file2:
	$(CC) -o file2 2/2.c
file3:
	$(CC) -o file3 3/3.c
file4:
	$(CC) -o file4 4/4.c

clean:
	rm -rf $(OBJS)

